
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
     - static_configs:
       - targets:
         - alertmanager-greyscale-image-converter:9093

scrape_configs:
  - job_name: 'node js scrape'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['greyscale-image-converter:3000']