
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node js scrape'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['greyscale-image-converter:3000']