{
 "title": "Greyscale Image Converter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{application=\"$application\", instance=\"$instance\"} /1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage (s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_heap_size_used_bytes{application=\"$application\", instance=\"$instance\"}) * 100 /sum(nodejs_heap_size_total_bytes{application=\"$application\", instance=\"$instance\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag (s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Upload Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(upload_success[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(upload_failure[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(http_errors{application=\"$application\", instance=\"$instance\",}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}